"use strict";
const TOTAL_LEVELS=100,QUESTIONS_PER_LEVEL=10,POINTS_PER_QUESTION=10,LEVEL_BONUS=100,STARTING_LIVES=3,QUESTION_TIME=20,SAVE_KEY="jungleNumberPuzzleProgressV2";
let questions=[],currentLevel=1,currentQuestionInLevel=1,score=0,lives=3,streak=0,selectedAnswer=null,submitted=false,timer=null,timeLeft=QUESTION_TIME,gameSoundOn=true,backgroundSoundOn=true;
const $=id=>document.getElementById(id),homeScreen=$("homeScreen"),gameScreen=$("gameScreen"),playBtn=$("playBtn"),resetProgressBtn=$("resetProgressBtn"),homeBtn=$("homeBtn"),savedProgressEl=$("savedProgress"),levelEl=$("level"),scoreEl=$("score"),livesEl=$("lives"),streakEl=$("streak"),questionNumberEl=$("questionNumber"),levelProgressLevel=$("levelProgressLevel"),levelProgressBar=$("levelProgressBar"),overallProgressBar=$("overallProgressBar"),overallProgressText=$("overallProgressText"),timerEl=$("timer"),timerBarEl=$("timerBar"),timerSection=document.querySelector(".timer-section"),questionTextEl=$("questionText"),puzzleEl=$("puzzle"),answersEl=$("answers"),messageEl=$("message"),submitBtn=$("submitBtn"),nextBtn=$("nextBtn"),gameOverEl=$("gameOver"),levelCompleteEl=$("levelComplete"),winScreenEl=$("winScreen"),finalScoreEl=$("finalScore"),winScoreEl=$("winScore"),continueBtn=$("continueBtn"),restartBtn=$("restartBtn"),winRestartBtn=$("winRestartBtn"),backgroundSoundBtn=$("backgroundSoundBtn"),gameSoundBtn=$("gameSoundBtn"),jungleSound=$("jungleSound"),elephantSound=$("elephantSound"),monkeySound=$("monkeySound"),tigerSound=$("tigerSound");
function random(a,b){return Math.floor(Math.random()*(b-a+1))+a}function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=random(0,i);[a[i],a[j]]=[a[j],a[i]]}return a}
function makeAnswers(c,l){let s=new Set([c]),g=Math.max(2,Math.floor(l/10)+1),n=0;while(s.size<4&&n++<200){let m=random(1,4),w=m===1?c+random(1,4+g):m===2?c-random(1,4+g):m===3?c+random(5,10+g):c-random(5,10+g);if(w<0)w=Math.abs(w);if(w!==c)s.add(w)}let f=c+1;while(s.size<4){if(!s.has(f))s.add(f);f++}let o=shuffle([...s]);return{options:o,answer:o.indexOf(c)}}
function addition(l){let m=15+l*5,a=random(5,m),b=random(5,m),c=a+b,r=makeAnswers(c,l);return{type:"addition",text:`${a} + ${b} = ?`,question:"Add the numbers.",...r}}
function subtraction(l){let m=15+l*5,a=random(10,m),b=random(1,m);if(b>a)[a,b]=[b,a];let c=a-b,r=makeAnswers(c,l);return{type:"subtraction",text:`${a} - ${b} = ?`,question:"Subtract the smaller number from the larger number.",...r}}
function multiplication(l){let m=Math.min(30,3+Math.floor(l/3)),a=random(2,m),b=random(2,m),c=a*b,r=makeAnswers(c,l);return{type:"multiplication",text:`${a} × ${b} = ?`,question:"Multiply the numbers.",...r}}
function division(l){let d=random(2,Math.min(15,3+Math.floor(l/7))),c=random(2,5+Math.floor(l/4)),x=d*c,r=makeAnswers(c,l);return{type:"division",text:`${x} ÷ ${d} = ?`,question:"Divide the numbers.",...r}}
function addSeq(l){let s=random(1,Math.min(20,2+Math.floor(l/7))),a=random(1,20+l*2),n=[0,1,2,3].map(i=>a+s*i),c=a+s*4,r=makeAnswers(c,l);return{type:"add-sequence",text:`${n.join(", ")}, ?`,question:`What comes next? Add ${s} each time.`,...r}}
function subSeq(l){let s=random(1,Math.min(15,2+Math.floor(l/7))),a=random(30,70+l*2),n=[0,1,2,3].map(i=>a-s*i),c=a-s*4,r=makeAnswers(c,l);return{type:"sub-sequence",text:`${n.join(", ")}, ?`,question:`What comes next? Subtract ${s} each time.`,...r}}
function squareSeq(l){let a=random(1,Math.min(15,3+Math.floor(l/12))),n=[0,1,2,3].map(i=>(a+i)**2),c=(a+4)**2,r=makeAnswers(c,l);return{type:"square",text:`${n.join(", ")}, ?`,question:"Find the next square number.",...r}}
function missing(l){let a=random(5,20+l*2),b=random(2,15+Math.floor(l/2)),t=a+b,r=makeAnswers(b,l);return{type:"missing",text:`${a} + ? = ${t}`,question:"Find the missing number.",...r}}
function doubleSeq(l){let a=random(2,8+Math.floor(l/10)),n=[a,a*2,a*4,a*8],c=a*16,r=makeAnswers(c,l);return{type:"double",text:`${n.join(", ")}, ?`,question:"What comes next? Each number is doubled.",...r}}
function createQuestion(l,num){let t=l<=10?[addition,subtraction,addSeq]:l<=25?[addition,subtraction,multiplication,division,addSeq,subSeq]:[addition,subtraction,multiplication,division,addSeq,subSeq,squareSeq,missing,doubleSeq];return t[(num-1)%t.length](l)}
function generateQuestions(){questions=[];let used=new Set;for(let l=1;l<=TOTAL_LEVELS;l++)for(let n=1;n<=QUESTIONS_PER_LEVEL;n++){let q,s,a=0;do{q=createQuestion(l,n);s=`${l}|${q.type}|${q.text}`}while(used.has(s)&&++a<300);used.add(s);q.level=l;q.number=n;questions.push(q)}console.log("Created",questions.length,"puzzles")}
function loadSaved(){try{return JSON.parse(localStorage.getItem(SAVE_KEY))}catch{return null}}function save(){localStorage.setItem(SAVE_KEY,JSON.stringify({unlockedLevel:currentLevel,score,streak}))}
function updateLives(){livesEl.textContent=[0,1,2].map(i=>i<lives?"❤️":"🖤").join(" ")}
function updateProgress(){levelEl.textContent=currentLevel;levelProgressLevel.textContent=currentLevel;questionNumberEl.textContent=currentQuestionInLevel;levelProgressBar.style.width=`${currentQuestionInLevel/10*100}%`;overallProgressText.textContent=`Level ${currentLevel} / ${TOTAL_LEVELS}`;overallProgressBar.style.width=`${((currentLevel-1)*10+currentQuestionInLevel)/TOTAL_QUESTIONS*100}%`}
function updateUI(){scoreEl.textContent=score;streakEl.textContent=streak;updateLives();updateProgress()}
function closePopups(){gameOverEl.classList.remove("show");levelCompleteEl.classList.remove("show");winScreenEl.classList.remove("show")}
function loadQuestion(){clearInterval(timer);let i=(currentLevel-1)*10+currentQuestionInLevel-1,q=questions[i];if(!q)return showWin();selectedAnswer=null;submitted=false;nextBtn.disabled=true;submitBtn.disabled=false;messageEl.textContent="";messageEl.className="message";questionTextEl.textContent=q.question;puzzleEl.textContent=q.text;answersEl.innerHTML="";q.options.forEach((o,i)=>{let b=document.createElement("button");b.type="button";b.className="answer-button";b.innerHTML=`<span class="answer-letter">${String.fromCharCode(65+i)}</span><span class="answer-text">${o}</span>`;b.onclick=()=>selectAnswer(i);answersEl.appendChild(b)});updateUI();startTimer()}
function selectAnswer(i){if(submitted)return;selectedAnswer=i;document.querySelectorAll(".answer-button").forEach(b=>b.classList.remove("selected"));document.querySelectorAll(".answer-button")[i]?.classList.add("selected")}
function disableAnswers(){document.querySelectorAll(".answer-button").forEach(b=>b.disabled=true)}
function playGameSound(s){if(!gameSoundOn||!s)return;s.currentTime=0;s.play().catch(()=>{})}function playBackgroundSound(){if(backgroundSoundOn){jungleSound.volume=.25;jungleSound.play().catch(()=>{})}}
function submitAnswer(){if(submitted)return;if(selectedAnswer===null){messageEl.textContent="⚠️ Select an answer first.";messageEl.className="message error";return}submitted=true;clearInterval(timer);submitBtn.disabled=true;disableAnswers();let q=questions[(currentLevel-1)*10+currentQuestionInLevel-1],b=document.querySelectorAll(".answer-button");if(selectedAnswer===q.answer){streak++;let gained=POINTS_PER_QUESTION+Math.max(0,timeLeft-10)+Math.min(30,streak*2);score+=gained;b[q.answer].classList.add("correct");messageEl.textContent=`🐘 Correct! +${gained} points`;messageEl.className="message success";playGameSound(elephantSound);save()}else{b[selectedAnswer].classList.add("wrong");b[q.answer].classList.add("correct");lives--;streak=0;updateLives();messageEl.textContent="🐒 Wrong answer! You lost 1 life.";messageEl.className="message error";playGameSound(monkeySound);save();if(lives<=0){nextBtn.disabled=true;setTimeout(showGameOver,700);return}}updateUI();nextBtn.disabled=false}
function nextQuestion(){if(!submitted)return;playGameSound(tigerSound);if(currentQuestionInLevel===10){if(currentLevel>=100)return showWin();score+=LEVEL_BONUS;save();levelCompleteEl.classList.add("show");return}currentQuestionInLevel++;loadQuestion()}
function continueToNextLevel(){levelCompleteEl.classList.remove("show");currentLevel++;currentQuestionInLevel=1;lives=STARTING_LIVES;streak=0;save();loadQuestion()}
function startTimer(){clearInterval(timer);timeLeft=QUESTION_TIME;updateTimer();timer=setInterval(()=>{timeLeft--;updateTimer();if(timeLeft<=0){clearInterval(timer);timeUp()}},1000)}function updateTimer(){timerEl.textContent=timeLeft;timerBarEl.style.width=`${timeLeft/QUESTION_TIME*100}%`;timerSection.classList.toggle("timer-danger",timeLeft<=5)}
function timeUp(){if(submitted)return;submitted=true;submitBtn.disabled=true;disableAnswers();let q=questions[(currentLevel-1)*10+currentQuestionInLevel-1],b=document.querySelectorAll(".answer-button");b[q.answer].classList.add("correct");lives--;streak=0;updateLives();messageEl.textContent="⏰ Time's up! You lost 1 life.";messageEl.className="message error";playGameSound(monkeySound);save();if(lives<=0){nextBtn.disabled=true;setTimeout(showGameOver,700);return}nextBtn.disabled=false}
function showGameOver(){clearInterval(timer);finalScoreEl.textContent=score;gameOverEl.classList.add("show");levelCompleteEl.classList.remove("show");winScreenEl.classList.remove("show")}
function showWin(){clearInterval(timer);score+=LEVEL_BONUS;localStorage.removeItem(SAVE_KEY);winScoreEl.textContent=score;winScreenEl.classList.add("show");gameOverEl.classList.remove("show");levelCompleteEl.classList.remove("show")}
function restartCurrentLevel(){clearInterval(timer);closePopups();currentQuestionInLevel=1;lives=STARTING_LIVES;streak=0;save();loadQuestion()}
function startNewGame(){generateQuestions();let s=loadSaved();currentLevel=s?.unlockedLevel||1;score=s?.score||0;streak=s?.streak||0;currentQuestionInLevel=1;lives=STARTING_LIVES;homeScreen.classList.remove("show");gameScreen.classList.add("show");closePopups();loadQuestion()}
function showHome(){clearInterval(timer);gameScreen.classList.remove("show");homeScreen.classList.add("show");let s=loadSaved();savedProgressEl.textContent=s?`🌿 Continue from Level ${s.unlockedLevel} • Score ${s.score||0}`:"🌿 Start your jungle adventure from Level 1!"}
playBtn.onclick=startNewGame;resetProgressBtn.onclick=()=>{if(confirm("Reset saved progress?")){localStorage.removeItem(SAVE_KEY);showHome()}};homeBtn.onclick=showHome;submitBtn.onclick=submitAnswer;nextBtn.onclick=nextQuestion;continueBtn.onclick=continueToNextLevel;restartBtn.onclick=restartCurrentLevel;winRestartBtn.onclick=()=>{localStorage.removeItem(SAVE_KEY);currentLevel=1;currentQuestionInLevel=1;score=0;streak=0;lives=3;generateQuestions();closePopups();loadQuestion()};backgroundSoundBtn.onclick=()=>{backgroundSoundOn=!backgroundSoundOn;backgroundSoundBtn.textContent=backgroundSoundOn?"🎵 Jungle Sound ON":"🔇 Jungle Sound OFF";if(backgroundSoundOn)playBackgroundSound();else jungleSound.pause()};gameSoundBtn.onclick=()=>{gameSoundOn=!gameSoundOn;gameSoundBtn.textContent=gameSoundOn?"🔊 Game Sound ON":"🔇 Game Sound OFF"};document.addEventListener("click",function once(){playBackgroundSound();document.removeEventListener("click",once)});generateQuestions();showHome();
